version: '3.8'

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    # Remove depends_on since we're using external Qdrant Cloud

# Remove volumes section since we don't need local Qdrant storage